<?php

namespace Database\Seeders;

use App\Models\Genre;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'img' => 'mhaprod.jpg',
                'name' => 'My Hero Academia',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Kohei Horikoshi',
                'date' => '2016-04-14',
                'fv_editor' => 'Ki-oon',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Dans un monde où 80% de la population possède un super‑pouvoir appelé alter, les héros font partie de la vie quotidienne. Et les super‑vilains aussi ! Face à eux se dresse l'invincible All Might, le plus puissant des héros ! Le jeune Izuku Midoriya en est un fan absolu. Il n'a qu'un rêve : entrer à la Hero Academia pour suivre les traces de son idole. Le problème, c'est qu'il fait partie des 20 % qui n'ont aucun pouvoir... Son destin est bouleversé le jour où sa route croise celle d'All Might en personne ! Ce dernier lui offre une chance inespérée de voir son rêve se réaliser. Pour Izuku, le parcours du combattant ne fait que commencer !",
                'language' => 'Français',
                'isbn10' => '235592483',
                'isbn30' => '978-2355929489',
                'pages' => '196',
                'weight' => '200',
                'size' => '12.1 x 1.7 x 17.8',
                'title' => 'Boku no Hero Academia / 僕のヒーローアカデミア',
                'origin' => 'Japon',
                'fv_volumes_number' => '28',
                'ov_volumes_number' => '30',
                'genres' => [
                    '1'
                ]
            ],
            [
                'img' => 'snk.jpg',
                'name' => 'L\'attaque des Titans',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Hajime Isayama',
                'date' => '2013-06-26',
                'fv_editor' => 'Pika',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Le monde appartient désormais aux Titans, des êtres gigantesques qui ont presque décimé l’Humanité. Voilà une centaine d’années, les derniers rescapés ont bâti une place forte, une cité cernée d’une haute muraille au sein de laquelle vivent aujourd’hui leurs descendants. Parqués, ignorants tout du monde extérieur, ils s’estiment au moins à l’abri de ces effroyables êtres qui ne feraient d’eux qu’une bouchée. Hélas, cette illusion de sécurité vole en éclats le jour où surgit un Titan démesuré, encore bien plus colossal que tous les autres. S’engage alors un combat désespéré pour la survie du genre humain...",
                'language' => 'Français',
                'isbn10' => '281161169X',
                'isbn30' => '978-2811611699',
                'pages' => '192',
                'weight' => '200',
                'size' => '12 x 1.5 x 18',
                'title' => 'Shingeki no Kyojin / 進撃の巨人',
                'origin' => 'Japon',
                'fv_volumes_number' => '34',
                'ov_volumes_number' => '34',
                'genres' => [
                    '1',
                    '3',
                ]
            ],
            [
                'img' => 'berserk.jpg',
                'name' => 'Berserk',
                'category_id' => '2',
                'volume' => '1',
                'author' => 'Kentaro Miura',
                'date' => '2004-10-06',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Hakusensha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Guts, le guerrier noir, promène son imposante silhouette de routes en villages. Sur son passage, les cadavres s'amoncellent et il laisse derrière lui des torrents de sang. Le corps vêtu de noir, il porte sur son dos une épée aussi haute qu'un homme. Sur son cou, une marque mystérieuse le condamne à être poursuivi jour et nuit par des démons. Puck, l'elfe facétieux, croise un jour le chemin de cette machine à tuer. Quelles horreurs a-t-il pu connaître pour être animé d'une telle soif de vengeance ? Alors que le monde sombre inextricablement dans le chaos, Guts règle ses comptes avec les forces démoniaques qui resserrent leur emprise sur la destinée des hommes. Une époque s'achève... Au fil des années, « Berserk » est devenu au Japon u n classique de l'heroic fantasy. Kentarô Miura y déploie ses talents de scénariste et son imagination débordante. La série abonde de scènes d'anthologies et baigne dans une violence implacable : pas étonnant que « Berserk » soit devenu une référence pour les amoureux de Tolkien et de jeux de rôles. En France, la série a déjà ses fans, qui voient leur attente récompensée : la série est publiée en sens de lecture et format original, et les 7 premiers volumes sont prévus pour paraître mensuellement. L'un des mangas les plus attendus de l'année !",
                'language' => 'Français',
                'isbn10' => '2723448126',
                'isbn30' => '978-2723448123',
                'pages' => '224',
                'weight' => '299',
                'size' => '13 x 1.8 x 18',
                'title' => 'Berserk / ベルセルク',
                'origin' => 'Japon',
                'fv_volumes_number' => '41',
                'ov_volumes_number' => '41',
                'genres' => [
                    '1',
                    '2',
                    '3',
                    '5',
                    '8',
                    '9'
                ]
            ],
            [
                'img' => 'op.jpg',
                'name' => 'One Piece',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Eiichiro Oda',
                'date' => '2013-07-03',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Nous sommes à l'ère des pirates. Luffy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le “One Piece”, un fabuleux trésor. Seulement, Luffy a avalé un fruit du démon qui l'a transformé en homme élastique. Depuis, il est capable de contorsionner son corps dans tous les sens, mais il a perdu la faculté de nager. Avec l'aide de ses précieux amis, il va devoir affronter de redoutables pirates dans des aventures toujours plus rocambolesques.
                Également adapté en dessin animé pour la télévision et le cinéma, One Piece remporte un formidable succès à travers le monde. Les aventures de Luffy au chapeau de paille ont désormais gagné tous les lecteurs, qui se passionnent chaque trimestre pour les aventures exceptionnelles de leurs héros.",
                'language' => 'Français',
                'isbn10' => '2723488527',
                'isbn30' => '978-2723488525',
                'pages' => '208',
                'weight' => '200',
                'size' => '11.5 x 1.5 x 18',
                'title' => 'ONE PIECE / ワンピース',
                'origin' => 'Japon',
                'fv_volumes_number' => '101',
                'ov_volumes_number' => '102',
                'genres' => [
                    '1',
                    '2',
                    '9',
                ]
            ],
            [
                'img' => 'tg.jpg',
                'name' => 'Tokyo Ghoul',
                'category_id' => '2',
                'volume' => '1',
                'author' => 'Sui Ishida',
                'date' => '2013-08-27',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "À Tokyo, sévissent des goules, monstres cannibales se dissimulant parmi les humains pour mieux s’en nourrir. Étudiant timide, Ken Kaneki est plus intéressé par la jolie fille qui partage ses goûts pour la lecture que par ces affaires sordides, jusqu’au jour où il se fait attaquer par l’une de ces fameuses créatures. Mortellement blessé, il survit grâce à la greffe des organes de son agresseur… Remis de son opération, il réalise peu à peu qu’il est devenu incapable de se nourrir comme avant et commence à ressentir un appétit suspect envers ses congénères. C’est le début d’une descente aux enfers pour Kaneki, devenu malgré lui un hybride mi-humain, mi-goule.",
                'language' => 'Français',
                'isbn10' => '2723495612',
                'isbn30' => '978-2723495615',
                'pages' => '224',
                'weight' => '186',
                'size' => '13 x 1.7 x 18',
                'title' => 'Tokyo Ghoul / 東京喰種トーキョーグール',
                'origin' => 'Japon',
                'fv_volumes_number' => '14',
                'ov_volumes_number' => '14',
                'genres' => [
                    '1',
                    '5',
                    '9',
                ]
            ],
            [
                'img' => 'naruto.jpg',
                'name' => 'Naruto',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Masashi Kishimoto',
                'date' => '2002-03-09',
                'fv_editor' => 'Kana',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Naruto est un garçon un peu spécial. Il est toujours tout seul et son caractère fougueux ne l'aide pas vraiment à se faire apprécier dans son village. Malgré cela, il garde au fond de lui une ambition: celle de devenir un maître Hokage, la plus haute distinction dans l'ordre des ninjas, et ainsi obtenir la reconnaissance de ses pairs.",
                'language' => 'Français',
                'isbn10' => '2871294143',
                'isbn30' => '978-2871294146',
                'pages' => '208',
                'weight' => '200',
                'size' => '12 x 1.4 x 17.5',
                'title' => 'NARUTO / ナルト',
                'origin' => 'Japon',
                'fv_volumes_number' => '72',
                'ov_volumes_number' => '72',
                'genres' => [
                    '1',
                    '2',
                    '9',
                ]
            ],
            [
                'img' => 'opm.jpg',
                'name' => 'One Punch-Man',
                'category_id' => '2',
                'volume' => '1',
                'author' => 'Yusuke Murata',
                'date' => '2016-01-14',
                'fv_editor' => 'Kurokawa',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Saitama est un jeune homme sans emploi et sans réelle perspective d'avenir, jusqu'au jour où il décide de prendre sa vie en main. Son nouvel objectif : devenir un super-héros. Il s'entraîne alors sans relâche pendant trois ans et devient si puissant qu'il est capable d'éliminer ses adversaires d'un seul coup de poing. On le surnomme désormais One-Punch Man. Mais rapidement, l'euphorie du succès cède place à l'ennui, car lorsqu'on est si fort, les victoires perdent de leur saveur...",
                'language' => 'Français',
                'isbn10' => '2368522255',
                'isbn30' => '978-2368522257',
                'pages' => '192',
                'weight' => '181',
                'size' => '11.9 x 1.7 x 17.8',
                'title' => 'One Punch-Man / ワンパンマン',
                'origin' => 'Japon',
                'fv_volumes_number' => '25',
                'ov_volumes_number' => '28',
                'genres' => [
                    '1',
                    '4',
                ]
            ],
            [
                'img' => 'dt.jpg',
                'name' => 'Death Note',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Tsugumi Ohba',
                'date' => '2007-01-18',
                'fv_editor' => 'Kana',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Light Yagami ramasse un étrange carnet oublié dans la cour de son lycée. Selon les instructions du carnet, la personne dont le nom est écrit dans les pages du Death Note mourra dans les 40 secondes !! Quelques jours plus tard, Light fait la connaissance de l'ancien propriétaire du carnet : Ryûk, un dieu de la mort ! Poussé par l'ennui, il a fait entrer le carnet sur terre. Ryûk découvre alors que Light a déjà commencé à remplir son carnet...",
                'language' => 'Français',
                'isbn10' => '2505000328',
                'isbn30' => '978-2505000327',
                'pages' => '210',
                'weight' => '159',
                'size' => '12 x 1.3 x 17.6',
                'title' => 'DEATH NOTE / デスノート',
                'origin' => 'Japon',
                'fv_volumes_number' => '13',
                'ov_volumes_number' => '13',
                'genres' => [
                    '8',
                    '12',
                    '13',
                ]
            ],
            [
                'img' => 'bleach.jpg',
                'name' => 'Bleach',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Tite Kubo',
                'date' => '2003-07-02',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Adolescent de quinze ans, Ichigo Kurosaki possède un don particulier : celui de voir les esprits. Un jour, il croise la route d'une belle Shinigami (un être spirituel) en train de pourchasser une \"âme perdue\", un esprit maléfique qui hante notre monde et n'arrive pas à trouver le repos.Mise en difficulté par son ennemi, la jeune fille décide alors de prêter une partie de ses pouvoirs à Ichigo, mais ce dernier hérite finalement de toute la puissance du Shinigami. Contraint d'assumer son nouveau statut, Ichigo va devoir gérer ses deux vies : celle de lycéen ordinaire, et celle de chasseur de démons... Bleach est l'oeuvre d'un mangaka prometteur, Taito Kubo, et le dernier succès des Editions Shueisha. Manga d'action au rythme trépidant, au graphisme soigné et à l'intrigue palpitante, Bleach est la nouvelle bonne surprise du manga au pays du Soleil Levant.",
                'language' => 'Français',
                'isbn10' => '2723442276',
                'isbn30' => '978-2723442275',
                'pages' => '192',
                'weight' => '200',
                'size' => '11.5 x 1.5 x 18',
                'title' => 'BLEACH / ブリーチ',
                'origin' => 'Japon',
                'fv_volumes_number' => '74',
                'ov_volumes_number' => '74',
                'genres' => [
                    '1',
                    '2',
                    '9',
                ]
            ],
            [
                'img' => 'opp.jpg',
                'name' => 'Bonne Nuit Punpun',
                'category_id' => '2',
                'volume' => '1',
                'author' => 'Inio Asano',
                'date' => '2012-02-02',
                'fv_editor' => 'Kana',
                'ov_editor' => 'Shōgakukan',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "La vie n'est pas rose pour Punpun. À la maison, ses parents se disputent souvent, les adultes de son entourage sont tous névrosés, et la fille qu'il aime vient de déménager. Heureusement, une nouvelle élève arrive à l'école. Elle s'appelle Aiko, et Punpun en tombe fou amoureux dès le premier regard. Mais, avec sa timidité, il ne va pas être facile d'attirer son regard, sans compter que son père est envoyé en prison et que son oncle Yuichi vient vivre avec lui...",
                'language' => 'Français',
                'isbn10' => '2505014132',
                'isbn30' => '978-2505014133',
                'pages' => '224',
                'weight' => '180',
                'size' => '12.9 x 2.4 x 18.1',
                'title' => 'Oyasumi Punpun / おやすみプンプン',
                'origin' => 'Japon',
                'fv_volumes_number' => '13',
                'ov_volumes_number' => '13',
                'genres' => [
                    '3',
                    '7',
                    '14',
                ]
            ],
            [
                'img' => 'ft.jpg',
                'name' => 'Fairy Tail',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Hiro Mashima',
                'date' => '2008-09-10',
                'fv_editor' => 'Pika',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Les guildes magiques sont des associations. Elles proposent différentes tâches aux magiciens, allant de la recherche d'un objet à l'attaque en règle. Lucy, une jeune fille, rêve de devenir magicienne. Un jour, elle rencontre Natsu, un magicien maîtrisant le feu, ce dernier l'invite alors à rejoindre sa guilde. Il s'agit de la célèbre Fairy Tail, le sujet de tous les rêves de Lucy. Mais celle-ci est bien mystérieuse et semble être à l'origine de nombreux scandales.",
                'language' => 'Français',
                'isbn10' => '2845999143',
                'isbn30' => '978-2845999145',
                'pages' => '192',
                'weight' => '249',
                'size' => '12 x 1.2 x 18',
                'title' => 'FAIRY TAIL / フェアリーテイル',
                'origin' => 'Japon',
                'fv_volumes_number' => '63',
                'ov_volumes_number' => '63',
                'genres' => [
                    '1',
                    '2',
                    '9',
                ]
            ],
            [
                'img' => 'fma.jpg',
                'name' => 'Fullmetal Alchemist',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Hiromu Arakawa',
                'date' => '2005-09-08',
                'fv_editor' => 'Kurokawa',
                'ov_editor' => 'Square Enix',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "En voulant ressusciter leur mère, Edward et Alphonse Elric utilisent une technique alchimique interdite : la transmutation humaine. Seulement, l'expérience tourne mal : Edward perd un bras et une jambe et Alphonse, son corps, son esprit se retrouvant prisonnier d'une armure. Devenu un alchimiste d'État, Edward, surnommé le Fullmetal Alchemist, se lance, avec l'aide de son frère, à la recherche de la pierre philosophale, seule chance de retrouver leurs corps. Les deux frères commencent à enquêter sur un homme étrange, \" le fondateur \", qui passe pour un faiseur de miracles...",
                'language' => 'Français',
                'isbn10' => '2351420179',
                'isbn30' => '978-2351420171',
                'pages' => '192',
                'weight' => '204',
                'size' => '11.9 x 1.6 x 17.8',
                'title' => 'Fullmetal Alchemist / 鋼の錬金術師',
                'origin' => 'Japon',
                'fv_volumes_number' => '27',
                'ov_volumes_number' => '27',
                'genres' => [
                    '1',
                    '2',
                    '3',
                    '9',
                ]
            ],
            [
                'img' => 'solol.jpg',
                'name' => 'Solo Leveling',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Chugong',
                'date' => '2021-04-07',
                'fv_editor' => 'Kbooks',
                'ov_editor' => 'Kakao',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Lorsque d'étranges portails sont apparus aux quatre coins du monde, l'humanité a dû trouver une parade pour ne pas finir massacrée entre les griffes des monstres qu'ils ont apportés avec eux. Dans le même temps, certaines personnes ont développé des capacités permettant de chasser. Ces combattants intrépides n'hésitent pas à foncer au coeur des donjons pour combattre les créatures qu'ils abritent.",
                'language' => 'Français',
                'isbn10' => '2382880295',
                'isbn30' => '978-2382880296',
                'pages' => '224',
                'weight' => '430',
                'size' => '15.1 x 1.4 x 21.4',
                'title' => 'Solo Leveling / 나 혼자만 레벨업',
                'origin' => 'Corée du Sud',
                'fv_volumes_number' => '5',
                'ov_volumes_number' => '14',
                'genres' => [
                    '1',
                    '2',
                    '9',
                ]
            ],
            [
                'img' => 'tpn.jpg',
                'name' => 'The Promised Neverland',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Kaiu Shirai',
                'date' => '2018-04-25',
                'fv_editor' => 'Kazé',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Emma, Norman et Ray coulent des jours heureux à l'orphelinat Grace Field House. Entourés de leurs petits frères et soeurs, ils s'épanouissent sous l'attention pleine de tendresse de « Maman », qu'ils considérent comme leur véritable mère. Mais tout bascule le soir où ils découvrent l'abominable réalité qui se cache derrière la façade de leur vie paisible ! Ils doivent s'échapper, c'est une question de vie ou de mort !",
                'language' => 'Français',
                'isbn10' => '2820332234',
                'isbn30' => '978-2820332233',
                'pages' => '193',
                'weight' => '136',
                'size' => '11.4 x 1.4 x 17.8',
                'title' => 'Yakusoku no Neverland / 約束のネバーランド',
                'origin' => 'Japon',
                'fv_volumes_number' => '20',
                'ov_volumes_number' => '20',
                'genres' => [
                    '2',
                    '3',
                    '9',
                    '10',
                    '12',
                    '14',
                ]
            ],
            [
                'img' => 'kny.jpg',
                'name' => 'Demon Slayer',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Koyoharu Gotouge',
                'date' => '2019-09-18',
                'fv_editor' => 'Panini',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Le Japon, au début du XXe siècle (ère Taisho). Un jeune vendeur de charbon nommé Tanjiro mène une vie sans histoire dans les montagnes, jusqu’au jour tragique où il découvre son village et sa famille massacrés par un démon. La seule survivante de cette tragédie est sa jeune soeur Nezuko. Hélas, au contact du démon, elle s’est métamorphosée en monstre féroce... Afin de renverser le processus et de venger sa famille, Tanjiro décide de partir en quête de vérité. Pour le jeune héros et sa soeur, c’est une longue aventure de sang et d’acier qui commence !",
                'language' => 'Français',
                'isbn10' => '2809482314',
                'isbn30' => '978-2809482317',
                'pages' => '192',
                'weight' => '200',
                'size' => '11.6 x 1.7 x 17.5',
                'title' => 'Kimetsu no Yaiba / 鬼滅の刃',
                'origin' => 'Japon',
                'fv_volumes_number' => '23',
                'ov_volumes_number' => '23',
                'genres' => [
                    '1',
                    '2',
                    '9',
                ]
            ],
            [
                'img' => 'cm.jpg',
                'name' => 'Chainsaw Man',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Tatsuki Fujimoto',
                'date' => '2020-03-11',
                'fv_editor' => 'Kazé',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Pour rembourser ses dettes, Denji, jeune homme dans la dèche la plus totale, est exploité en tant que Devil Hunter avec son chien-démon-tronçonneuse, Pochita . Mais suite à une cruelle trahison, il voit enfin une possibilité de se tirer des bas-fonds où il croupit ! Devenu surpuissant après sa fusion avec Pochita, Denji est recruté par une organisation de Devil Hunters et part à la chasse aux démons...",
                'language' => 'Français',
                'isbn10' => '2820337821',
                'isbn30' => '978-2820337825',
                'pages' => '192',
                'weight' => '130',
                'size' => '11.5 x 1.3 x 17.7',
                'title' => 'Chainsaw Man / チェンソーマン',
                'origin' => 'Japon',
                'fv_volumes_number' => '11',
                'ov_volumes_number' => '11',
                'genres' => [
                    '1',
                    '2',
                ]
            ],
            [
                'img' => 'slamdunk31.jpg',
                'name' => 'Slam Dunk',
                'category_id' => '1',
                'volume' => '31',
                'author' => 'Takehiko Inoue',
                'date' => '2004-12-01',
                'fv_editor' => 'Kana',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Nous sommes dans les tous derniers moments du match du tournoi interlycée. Il reste une minute de jeu et l'équipe de Sannô mène 76 à 71. Sakuragi s'est blessé en retombant, Rukawa semble en perte d'énergie, Akagi \"le Gorille\" n'y crois plus vraiment... Si près du but... L'équipe de Shôhoku trouvera-t-elle l'énergie nécessaire pour remonter cet écart à seulement une minute de la fin du jeu... Et puis, ne dit-on pas que l'important est de participer...? Et la série Slam Dunk se clôture sur ce volume 31...",
                'language' => 'Français',
                'isbn10' => '287129660X',
                'isbn30' => '978-2871296607',
                'pages' => '184',
                'weight' => '141',
                'size' => '11.8 x 1.2 x 17.7',
                'title' => 'SLAM DUNK / スラムダンク',
                'origin' => 'Japon',
                'fv_volumes_number' => '31',
                'ov_volumes_number' => '31',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'kuroko17.jpg',
                'name' => 'Kuroko\'s Basket',
                'category_id' => '1',
                'volume' => '17',
                'author' => 'Tadatoshi Fujimaki',
                'date' => '2014-09-03',
                'fv_editor' => 'Kazé',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "En quarts de finale, le match qui oppose Seirin au redoutable cinq majeur de Yôsen est sur le point de commencer. Kuroko et ses amis seront confrontés à un jeu d’une toute autre envergure. Parviendront-ils à briser le fameux Bouclier de Zeus qui se dressent devant eux ? D’autant que Kagami va devoir faire face à celui qu’il considérait comme son grand frère : Himuro !",
                'language' => 'Français',
                'isbn10' => '2820317685',
                'isbn30' => '978-2820317681',
                'pages' => '196',
                'weight' => '130',
                'size' => '11.5 x 1.5 x 17.6',
                'title' => 'Kuroko no Basket / 黒子のバスケ',
                'origin' => 'Japon',
                'fv_volumes_number' => '30',
                'ov_volumes_number' => '30',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'haikyu24.jpg',
                'name' => 'Haikyu !!',
                'category_id' => '1',
                'volume' => '24',
                'author' => 'Haruichi Furudate',
                'date' => '2017-10-18',
                'fv_editor' => 'Kazé',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Au sein de Karasuno, en pleine préparation du Printemps Interlycées, l'annonce de la sélection de Kageyama pour le stage d'entraînement de l'équipe nationale Espoirs sonne comme un véritable coup de tonnerre ! Alors que le \"Roi du Terrain\" monte en puissance, Hinata n'a malheureusement pas été sélectionné malgré son désir de progresser... Ce qui ne l'empêche pas de faire une apparition surprise dans le stage des meilleurs joueurs de seconde du département !",
                'language' => 'Français',
                'isbn10' => '2820329179',
                'isbn30' => '978-2820329172',
                'pages' => '192',
                'weight' => '140',
                'size' => '11.5 x 1.2 x 17.5',
                'title' => 'Haikyuu!! / ハイキュー!!',
                'origin' => 'Japon',
                'fv_volumes_number' => '45',
                'ov_volumes_number' => '45',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'e2121.jpg',
                'name' => 'Eyeshield 21',
                'category_id' => '1',
                'volume' => '21',
                'author' => 'Riichirô Inagaki',
                'date' => '2006-02-01',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Difficile de se faire respecter quand on est depuis toujours le souffre-douleur de ses camarades ! Sena le sait bien, lui qui est constamment chargé de faire le « coursier » pour tous ceux qui le briment. Pour cette rentrée scolaire, Sena veut tourner la page et se décide à rentrer dans un club. Malheureusement pour lui, il croise le chemin de Hiruma, le responsable du club de football américain, un être psychotique prêt à toutes les combines pour faire rentrer des joueurs dans son club. Lorsqu'il découvre que Sena est doté d'un jeu de jambe hors du commun, il décide de jeter son dévolu sur le pauvre garçon. Et ils n'ont pas intérêt à tarder de recruter les onze autres joueurs manquants pour former une équipe, car le début du championnat inter lycéen débute... dans 24 heures ! Eye Shield 21 est la nouvelle bombe sportive du Shônen Jump, un mélange détonnant d'humour et d'action qui fait actuellement fureur au Japon ! Vous ne connaissez rien au foot américain ? Rassurez-vous, le héros non plus ! Preuve est faite, encore une fois, que les japonais sont capables de rendre passionnant n'importe quel sujet. Un futur hit du shônen en France !",
                'language' => 'Français',
                'isbn10' => '2723453774',
                'isbn30' => '978-2723453776',
                'pages' => '208',
                'weight' => '100',
                'size' => '11.5 x 1.5 x 18',
                'title' => 'Eyeshield 21 / アイシールド21',
                'origin' => 'Japon',
                'fv_volumes_number' => '37',
                'ov_volumes_number' => '37',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'ippo4.jpg',
                'name' => 'Ippo',
                'category_id' => '1',
                'volume' => '4',
                'author' => 'George Morikawa',
                'date' => '2007-09-13',
                'fv_editor' => 'Kurokawa',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Ippo Makunouchi est un jeune et timide lycéen de 16 ans qui n’a pas d’amis car il consacre tout son temps libre à aider sa mère, qui l'élève seule, dans l’entreprise familiale de location de bateaux de pêche. Il est couramment victime de brutalités et d’humiliations par une bande de voyous menée par Umezawa, un de ses camarades de classe. Un jour, un boxeur professionnel témoin de la scène, Mamoru Takamura, le sauve de ses bourreaux et emmène Ippo blessé au club de boxe Kamogawa, tenu par le boxeur retraité Genji Kamogawa, pour le soigner. Une fois Ippo réveillé, Takamura tente de lui remonter le moral en le persuadant de se défouler sur un sac de sable, expérience qui révèle chez lui une grande puissance de frappe et un talent inné pour la boxe. Se découvrant une passion pour ce sport et poussé par le désir de devenir fort, le jeune Ippo décide de devenir boxeur professionnel et commence son entraînement au sein du club vers les plus hauts niveaux.",
                'language' => 'Français',
                'isbn10' => '2351422069',
                'isbn30' => '978-2351422069',
                'pages' => '208',
                'weight' => '130',
                'size' => '11.5 x 1.5 x 18',
                'title' => 'Hajime no Ippo / はじめの一歩',
                'origin' => 'Japon',
                'fv_volumes_number' => '134',
                'ov_volumes_number' => '134',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'ag7.jpg',
                'name' => 'Air Gear',
                'category_id' => '1',
                'volume' => '7',
                'author' => 'Oh! Great',
                'date' => '2007-12-12',
                'fv_editor' => 'Pika',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Le grand jour approche... Les Kogarasu Maru peaufinent leur condition pour se préparer au combat contre les Behemoth. Agito est sûr de lui. Mais le doute s’installe dans la tête de certains membres de l’équipe. Il faut dire que l’événement est de taille. Le part war se joue dans un stade comble à l’ambiance endiablée, et il est diffusé dans le monde entier sur le Net. Le premier combat oppose deux styles, la force de Buccha face à la souplesse d’Hécatonchirès. Que le meilleur gagne...",
                'language' => 'Français',
                'isbn10' => '2845997957',
                'isbn30' => '978-2845997950',
                'pages' => '208',
                'weight' => '100',
                'size' => '12 x 1.5 x 18',
                'title' => 'Air Gear / エア・ギア',
                'origin' => 'Japon',
                'fv_volumes_number' => '37',
                'ov_volumes_number' => '37',
                'genres' => [
                    '1',
                    '4',
                    '6',
                    '8',
                    '16',
                ]
            ],
            [
                'img' => 'bluelock.jpg',
                'name' => 'Blue Lock',
                'category_id' => '1',
                'volume' => '7',
                'author' => 'Muneyuki Kaneshiro',
                'date' => '2021-06-02',
                'fv_editor' => 'Pika',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Coupe du monde 2018, l’équipe de football du Japon est éliminée en huitièmes de finale... Ce nouvel échec incite l’Union japonaise de football à fonder le “Blue Lock” : un centre de formation révolutionnaire rassemblant les 300 meilleurs attaquants lycéens du pays. L’objectif du coach du Blue Lock, Jinpachi Ego, est clair : détecter l’unique attaquant qui écrasera tous ses rivaux par son talent et son hyper-individualisme ! Pour Yoichi Isagi, joueur bouillonnant encore inconnu, il n’y a pas d’alternative... S’il veut survivre au programme hautement sélectif qui l’attend, il devra abandonner le jeu collectif et se transcender pour devenir l’attaquant ultime !",
                'language' => 'Français',
                'isbn10' => '2811650253',
                'isbn30' => '978-2811650254',
                'pages' => '208',
                'weight' => '202',
                'size' => '12 x 1.6 x 18',
                'title' => 'Blue Lock / ブルーロック',
                'origin' => 'Japon',
                'fv_volumes_number' => '9',
                'ov_volumes_number' => '18',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'climber15.jpg',
                'name' => 'The Climber',
                'category_id' => '2',
                'volume' => '15',
                'author' => ' Shin-Ichi Sakamoto',
                'date' => '2012-08-24',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Du souffle, il en faudra pour suivre ce récit à la fois haletant et contemplatif, qui place les lecteurs au contact (rugueux) de la montagne, sur le chemin ouvert par Buntarô Mori. Ce lycéen ombrageux et solitaire n'a jamais cherché à s'intégrer à la société. Mais au détour d'un défi lancé par un camarade de classe fan d'escalade, il entreprend la périlleuse ascension d'un bâtiment scolaire. En atteignant le toit, il se sent réellement vivant pour la première fois de sa vie, jusqu'ici rongée par l'ennui. La découverte de l'alpinisme va ensuite lui révéler un talent inné, et lui faire découvrir une incroyable sensation de plénitude, qui agit comme une drogue...",
                'language' => 'Français',
                'isbn10' => '8866342807',
                'isbn30' => '978-8866342809',
                'pages' => '191',
                'weight' => '240',
                'size' => '1.6 x 23.9 x 18.4',
                'title' => 'Kokou no Hito / 孤高の人',
                'origin' => 'Japon',
                'fv_volumes_number' => '17',
                'ov_volumes_number' => '17',
                'genres' => [
                    '3',
                    '16',
                ]
            ],
            [
                'img' => 'ballroom.jpg',
                'name' => 'Welcome to the Ballroom',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Takeuchi Tomo',
                'date' => '2021-06-25',
                'fv_editor' => 'NOEVE GRAFX',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Collégien en déroute, Tatara Fujita ne sait pas quoi faire de sa vie. Il na ni talent, ni passion, ni grande envie de chercher. Le hasard et une bande de caïds mal intentionnés lui feront rencontrer Kaname Sengoku, danseur professionnel qui à la suite dun quiproquo le traînera jusquà un nouveau studio de danse de salon. Tatara y découvre lunivers de la danse sportive. Ne serait-ce pas là le début dune nouvelle passion ?",
                'language' => 'Français',
                'isbn10' => '2490676814',
                'isbn30' => '978-2490676811',
                'pages' => '200',
                'weight' => '170',
                'size' => '11.5 x 2.8 x 18',
                'title' => 'Ballroom e Youkoso / ボールルームへようこそ',
                'origin' => 'Japon',
                'fv_volumes_number' => '4',
                'ov_volumes_number' => '11',
                'genres' => [
                    '3',
                    '4',
                    '6',
                    '16',
                ]
            ],
            [
                'img' => 'aod20.jpg',
                'name' => 'Ace of the Diamond',
                'category_id' => '1',
                'volume' => '20',
                'author' => 'Yuji Terajima',
                'date' => '2010-03-17',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "L'équipe de baseball du collège Akagi termine sa saison sans une seule victoire. Son lanceur, Eijun Sawamura, est impatient de prendre sa revanche avec ses coéquipiers, une fois au lycée. Mais il reçoit la visite d'une représentante du lycée réputé Seido qui veut le recruter. Peu enclin à quitter ses amis, il va quand même visiter les installations de Seido, où il rencontre un receveur de génie, Kazuya Miyuki. Cette rencontre va changer son destin et, après avoir reçu les encouragement de sa famille et de ses amis, il décide de rejoindre cette équipe. Dans une équipe d'élite rassemblant des lycéens du pays entier, Eijun va devoir se faire une place et viser le tournoi national avec ses nouveaux coéquipiers.",
                'language' => 'Français',
                'isbn10' => '4063842654',
                'isbn30' => '978-4063842654',
                'pages' => '208',
                'weight' => '140',
                'size' => '11.5 x 2.8 x 18',
                'title' => 'Diamond no Ace / ダイヤのA〈エース',
                'origin' => 'Japon',
                'fv_volumes_number' => '47',
                'ov_volumes_number' => '47',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'pedal17.jpg',
                'name' => 'Yowamushi Pedal',
                'category_id' => '1',
                'volume' => '17',
                'author' => 'Wataru Watanabe',
                'date' => '2021-05-04',
                'fv_editor' => 'Youtoo',
                'ov_editor' => 'Akita Shoten',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Sakamichi Onoda est un otaku qui effectue sa rentrée en première année de lycée. Il a l'intention de rejoindre le club d'anime et se faire des amis mais, par manque de membres, ledit club a été fermé. Il lui faut trouver suffisamment de membres pour le rouvrir. Pas découragé, il décide de trouver des compagnons pour rouvrir le club et réaliser son rêve : passer du temps à flâner entre amis dans le quartier Akihabara à Tokyo. Remarqué presque par hasard par Shunsuke Imaizumi puis par Shōkichi Naruko, il est convié à joindre le club de cyclisme. Curieux des sensations qui l'ont entraîné durant son expérience avec ces deux jeunes coureurs, il décide de donner sa chance au club.",
                'language' => 'Français',
                'isbn10' => '1975310632',
                'isbn30' => '978-1975310639',
                'pages' => '400',
                'weight' => '445',
                'size' => '14.73 x 3.94 x 20.83',
                'title' => 'Yowamushi Pedal / 弱虫ペダル',
                'origin' => 'Japon',
                'fv_volumes_number' => '64',
                'ov_volumes_number' => '77',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'sumo.jpg',
                'name' => 'Hinomaru Sumo',
                'category_id' => '1',
                'volume' => '1',
                'author' => 'Kawada',
                'date' => '2021-05-04',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Le club de sumo du lycée Ôdachi a beau être l’un des plus faibles de la ville, le jeune Hinomaru décide quand même de le rejoindre. Il faut dire que ni sa taille ni son gabarit ne font de lui un futur sumo… Pourtant, ce nouveau venu pourrait bien se révéler beaucoup plus fort que prévu… Réussira-t-il à atteindre le grade suprême de yokozuna ?! Découvrez le parcours de ce lycéen hors norme dans le monde enflammé du sumo !",
                'language' => 'Français',
                'isbn10' => '2344013016',
                'isbn30' => '978-2344013014',
                'pages' => '192',
                'weight' => '140',
                'size' => '11.5 x 1.3 x 18',
                'title' => 'Hinomaruzumou / 火ノ丸相撲',
                'origin' => 'Japon',
                'fv_volumes_number' => '28',
                'ov_volumes_number' => '28',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'dreamteam29.jpg',
                'name' => 'Dream Team',
                'category_id' => '1',
                'volume' => '29',
                'author' => 'Takeshi Hinata',
                'date' => '2016-06-01',
                'fv_editor' => 'Glénat',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Avec la nouvelle année scolaire qui commence, la réputation grandissante de Kuzuryu semble avoir éveillé de nombreuses vocations. Mais les candidats désireux de rejoindre le club de basket abandonnent bien vite lorsqu’ils découvrent la sévérité de l’entraînement. Kota Igarashi, que l’équipe a affronté lors du Monster Bash, fait partie des rares à tenir bon. Partagé entre sa soif de revanche et son admiration inavouée pour Sora, il pourrait bien devenir un atout sérieux pour Kuzuryu…",
                'language' => 'Français',
                'isbn10' => '2344012974',
                'isbn30' => '978-2344012970',
                'pages' => '416',
                'weight' => '120',
                'size' => '11.5 x 2.8 x 18',
                'title' => 'Ahiru no Sora / あひるの空',
                'origin' => 'Japon',
                'fv_volumes_number' => '48',
                'ov_volumes_number' => '51',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'real14.jpg',
                'name' => 'Real',
                'category_id' => '2',
                'volume' => '14',
                'author' => 'Takehiko Inoue',
                'date' => '2015-11-20',
                'fv_editor' => 'Kana',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "Takahashi décide finalement de reprendre un ballon en main. Mais il découvre vite que le handi-basket-ball est complètement différent du basket-ball ordinaire, et il devra tout recommencer à partir des fondamentaux. Est-ce que son ego sera suffisamment en sourdine pour lui permettre de redécouvrir sa vraie passion !?",
                'language' => 'Français',
                'isbn10' => '2505062994',
                'isbn30' => '978-2505062998',
                'pages' => '206',
                'weight' => '200',
                'size' => '13 x 1.4 x 18',
                'title' => 'Real / リアル',
                'origin' => 'Japon',
                'fv_volumes_number' => '15',
                'ov_volumes_number' => '15',
                'genres' => [
                    '3',
                    '16',
                ]
            ],
            [
                'img' => 'tennis33.jpg',
                'name' => 'Prince du Tennis',
                'category_id' => '1',
                'volume' => '33',
                'author' => 'Takeshi Konomi',
                'date' => '2011-10-05',
                'fv_editor' => 'Kana',
                'ov_editor' => 'Shūeisha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "La rencontre opposant Seigaku à Hyôtei pour les quarts de finale fait rage : aucune des deux équipes ne cède d'un pouce. Lors du match en simple n° 2, Tezuka joue contre Kabaji !! Il doit faire face à un joueur capable d'assimiler et de reproduire n'importe quelle technique. Pour le battre, il a recours au Hyakurenjitoku no kiwami. Son adversaire pourra-t-il s'approprier cette technique...?!",
                'language' => 'Français',
                'isbn10' => '2505011621',
                'isbn30' => '978-2505011620',
                'pages' => '192',
                'weight' => '159',
                'size' => '11.5 x 1.3 x 17.5',
                'title' => 'Tennis no Ouji-sama / テニスの王子様',
                'origin' => 'Japon',
                'fv_volumes_number' => '42',
                'ov_volumes_number' => '42',
                'genres' => [
                    '16',
                ]
            ],
            [
                'img' => 'chihayafuru.jpg',
                'name' => 'Chihayafuru',
                'category_id' => '1',
                'volume' => '33',
                'author' => 'Yuki Suetsugu',
                'date' => '2013-12-11',
                'fv_editor' => 'Pika',
                'ov_editor' => 'Kōdansha',
                'paperback_price' => '6.99',
                'digital_price' => '4.99',
                'quantity' => '20',
                'synopsis' => "En sixième, la petite Chihaya fait la connaissance d'Arata, un nouvel élève qui vient de Fukui. C'est un jeune garçon mature et peu bavard qui cache un talent tout particulier : il excelle à un jeu appelé karuta, qui regroupe les cent poèmes traditionnels du Hyakunin Isshu. Chihaya est très impressionnée par sa capacité à ramasser les bonnes cartes en une fraction de seconde, avec une ardeur inégalée. Mais de son côté, Arata est cloué sur place par la disposition naturelle que semble présenter Chihaya vis-à-vis de ce jeu…",
                'language' => 'Français',
                'isbn10' => '2811614095',
                'isbn30' => '978-2811614096',
                'pages' => '192',
                'weight' => '180',
                'size' => '12 x 1.5 x 18',
                'title' => 'Chihayafuru / ちはやふる',
                'origin' => 'Japon',
                'fv_volumes_number' => '40',
                'ov_volumes_number' => '50',
                'genres' => [
                    '6',
                    '7',
                    '16',
                ]
            ],
        ];

        foreach ($products as $product) {
            try {
                $tmp_product = Product::firstOrCreate([
                    'img' => $product['img'],
                    'name' => $product['name'],
                    'category_id' => $product['category_id'],
                    'volume' => $product['volume'],
                    'author' => $product['author'],
                    'date' => $product['date'],
                    'fv_editor' => $product['fv_editor'],
                    'ov_editor' => $product['ov_editor'],
                    'paperback_price' => $product['paperback_price'],
                    'digital_price' => $product['digital_price'],
                    'quantity' => $product['quantity'],
                    'synopsis' => $product['synopsis'],
                    'language' => $product['language'],
                    'isbn10' => $product['isbn10'],
                    'isbn30' => $product['isbn30'],
                    'pages' => $product['pages'],
                    'weight' => $product['weight'],
                    'size' => $product['size'],
                    'title' => $product['title'],
                    'origin' => $product['origin'],
                    'fv_volumes_number' => $product['fv_volumes_number'],
                    'ov_volumes_number' => $product['ov_volumes_number']
                ]);
                $tmp_product->genres()->attach(Genre::find($product['genres']));
            } catch (\Exception $exception) {
                if ($exception->getCode() == "23000") {
                    dump('Product "' . $product['name'] . '" already exist');
                } else {
                    dump($exception->getMessage());
                }
            }
        }
    }
}
